p8105\_hw3\_xz3078
================

## Problem 1

``` r
library(p8105.datasets)
data("instacart")
```

This dataset has 1384617 rows and 15 columns with variable names
order\_id, product\_id, add\_to\_cart\_order, reordered, user\_id,
eval\_set, order\_number, order\_dow, order\_hour\_of\_day,
days\_since\_prior\_order, product\_name, aisle\_id, department\_id,
aisle, department. Among these variables, “add\_to\_cart\_order” is
order in which each product was added to cart; “reordered” is a dummy
variable equals 1 if this prodcut has been ordered by this user in the
past, and 0 otherwise; “order\_number” is the order sequence number for
this user; “order\_dow” is the day of the week on which the order was
placed; “order\_hour\_of\_day” is the hour of the day on which the order
was placed; “days\_since\_prior\_order” is days since the last order,
capped at 30, NA if order\_number=1.

For example, the first row in “instacart” means the order id is 1; the
product id is 49302; it’s the first item added to the cart; it has been
ordered by this user before; the user id is 112108; this order belongs
in “train” evaluation set; the order sequence number for this user is 4;
the order is placed on Thursday 10am; 9 days since the last order; the
product is Bulgarian Yogurt; the aisle is yogurt with id 120; the
department is dairy eggs with id 16.

``` r
instacart %>%
  summarize(
    n_aisle = n_distinct(aisle))
```

    ## # A tibble: 1 x 1
    ##   n_aisle
    ##     <int>
    ## 1     134

``` r
instacart %>%
  group_by(aisle) %>%
  summarize(
    n_obs = n()) %>%
  arrange(desc(n_obs))
```

    ## # A tibble: 134 x 2
    ##    aisle                          n_obs
    ##    <chr>                          <int>
    ##  1 fresh vegetables              150609
    ##  2 fresh fruits                  150473
    ##  3 packaged vegetables fruits     78493
    ##  4 yogurt                         55240
    ##  5 packaged cheese                41699
    ##  6 water seltzer sparkling water  36617
    ##  7 milk                           32644
    ##  8 chips pretzels                 31269
    ##  9 soy lactosefree                26240
    ## 10 bread                          23635
    ## # ... with 124 more rows

There are 134 aisles, and fresh vegetables is the most items ordered
from.

``` r
instacart %>%
  group_by(aisle) %>%
  summarize(
    n_obs = n()) %>%
  filter(n_obs > 10000) %>%
  ggplot(aes(x = reorder(aisle, -n_obs), y= n_obs)) + 
    geom_point() +
  labs(y = "number of items ordered",
       x = "aisle") +
  theme(axis.text.x = element_text(angle=90, hjust=1))
```

![](p8105_hw3_xz3078_files/figure-gfm/unnamed-chunk-3-1.png)<!-- -->

There are 39 aisles with more than 10000 items ordered. The aisles with
the most items ordered are fresh vegetables, fresh fruits, and packaged
vegetables fruits.

``` r
instacart %>%
  filter(aisle %in% c("baking ingredients", "dog food care", "packaged vegetables fruits")) %>%
  group_by(aisle) %>%
  count(product_name, name = "n_product") %>%
  slice_max(n_product, n=3)
```

    ## # A tibble: 9 x 3
    ## # Groups:   aisle [3]
    ##   aisle                      product_name                              n_product
    ##   <chr>                      <chr>                                         <int>
    ## 1 baking ingredients         Light Brown Sugar                               499
    ## 2 baking ingredients         Pure Baking Soda                                387
    ## 3 baking ingredients         Cane Sugar                                      336
    ## 4 dog food care              Snack Sticks Chicken & Rice Recipe Dog T~        30
    ## 5 dog food care              Organix Chicken & Brown Rice Recipe              28
    ## 6 dog food care              Small Dog Biscuits                               26
    ## 7 packaged vegetables fruits Organic Baby Spinach                           9784
    ## 8 packaged vegetables fruits Organic Raspberries                            5546
    ## 9 packaged vegetables fruits Organic Blueberries                            4966

The three most popular items in “baking ingredients” are “Light Brown
Sugar” with 499 items, “Pure Baking Soda” 387 items, and “Cane Sugar”
with 336 items. The three most popular items in “dog food care” are
“Snack Sticks Chicken & Rice Recipe Dog Treats” with 30 items, “Organix
Chicken & Brown Rice Recipe” with 28 items, and “Small Dog Biscuits”
with 26 items. The three most popular items in “packaged vegetables
fruits” are “Organic Baby Spinach” 9784 items, “Organic Raspberries”
5546 items, and “Organic Blueberries” with 4966 items.

``` r
instacart %>%
  filter(product_name %in% c("Pink Lady Apples", "Coffee Ice Cream")) %>%
  select(product_name, order_dow, order_hour_of_day) %>%
  group_by(product_name, order_dow) %>%
  summarize(mean_hod = mean(order_hour_of_day)) %>%
  pivot_wider(
    names_from = "order_dow", 
    values_from = "mean_hod"
  ) %>%
  rename(Sunday = "0", Monday = "1", Tuesday = "2", Wednesday = "3", Thursday = "4", Friday = "5", Saturday = "6")
```

    ## `summarise()` has grouped output by 'product_name'. You can override using the `.groups` argument.

    ## # A tibble: 2 x 8
    ## # Groups:   product_name [2]
    ##   product_name     Sunday Monday Tuesday Wednesday Thursday Friday Saturday
    ##   <chr>             <dbl>  <dbl>   <dbl>     <dbl>    <dbl>  <dbl>    <dbl>
    ## 1 Coffee Ice Cream   13.8   14.3    15.4      15.3     15.2   12.3     13.8
    ## 2 Pink Lady Apples   13.4   11.4    11.7      14.2     11.6   12.8     11.9

The mean hour of the day at which Coffee Ice Cream are ordered from
Sunday to Saturday are 13.7, 14.3, 15.4, 15.3, 15.2, 12.3, and 13.8. The
mean hour of the day at which Pink Lady Apples are ordered from Sunday
to Saturday are 13.4, 11.4, 11.7, 14.3, 11.6, 12.8, and 11.9.

## Problem 2

``` r
library(p8105.datasets)
data("brfss_smart2010")
```

``` r
brfss = 
  brfss_smart2010 %>%
  janitor::clean_names() %>% 
  rename(state = locationabbr, location = locationdesc) %>%
  filter(topic == "Overall Health") %>%
  filter(response %in% c("Poor", "Fair", "Good", "Very good", "Excellent")) %>%
  mutate(response = ordered(response, levels = c("Poor", "Fair", "Good", "Very good", "Excellent"))) 
```

``` r
brfss %>%
  filter(year == 2002) %>%
  group_by(state) %>%
  summarize(
    n_location = n_distinct(location)) %>%
  filter(n_location >= 7)
```

    ## # A tibble: 6 x 2
    ##   state n_location
    ##   <chr>      <int>
    ## 1 CT             7
    ## 2 FL             7
    ## 3 MA             8
    ## 4 NC             7
    ## 5 NJ             8
    ## 6 PA            10

``` r
brfss %>%
  filter(year == 2010) %>%
  group_by(state) %>%
  summarize(
    n_location = n_distinct(location)) %>%
  filter(n_location >= 7)
```

    ## # A tibble: 14 x 2
    ##    state n_location
    ##    <chr>      <int>
    ##  1 CA            12
    ##  2 CO             7
    ##  3 FL            41
    ##  4 MA             9
    ##  5 MD            12
    ##  6 NC            12
    ##  7 NE            10
    ##  8 NJ            19
    ##  9 NY             9
    ## 10 OH             8
    ## 11 PA             7
    ## 12 SC             7
    ## 13 TX            16
    ## 14 WA            10

In 2002, CT, FL, MA, NC, NJ, PA were observed at 7 or more locations. In
2010, CA, CO, FL, MA, MD, NC, NE, NJ, NY, OH, PA, SC, TX, WA were
observed at 7 or more locations.

``` r
brfss %>%
  filter(response == "Excellent") %>%
  group_by(state, year) %>%
  mutate(mean_value = mean(data_value, na.rm = TRUE)) %>%
  select(year, state, mean_value) %>%
  distinct() %>%
  ggplot(aes(x = year, y = mean_value, color = state)) + 
    geom_line(alpha = .5)
```

![](p8105_hw3_xz3078_files/figure-gfm/unnamed-chunk-9-1.png)<!-- -->

We can see from the plot that there is a downward trend for the mean
data value for all states.

``` r
brfss %>%
  filter(year %in% c(2006, 2010), state == "NY") %>%
  group_by(year, response) %>%
  drop_na(data_value) %>%
  ggplot(aes(x = response, y = data_value)) + 
    geom_point() +
    facet_grid(. ~ year)
```

![](p8105_hw3_xz3078_files/figure-gfm/unnamed-chunk-10-1.png)<!-- -->

Make a two-panel plot showing, for the years 2006, and 2010,
distribution of data\_value for responses (“Poor” to “Excellent”) among
locations in NY State.

## Problem 3

``` r
accel=
  read_csv("./data/accel_data.csv") %>%
  janitor::clean_names() 
```

    ## Rows: 35 Columns: 1443

    ## -- Column specification --------------------------------------------------------
    ## Delimiter: ","
    ## chr    (1): day
    ## dbl (1442): week, day_id, activity.1, activity.2, activity.3, activity.4, ac...

    ## 
    ## i Use `spec()` to retrieve the full column specification for this data.
    ## i Specify the column types or set `show_col_types = FALSE` to quiet this message.
